name: Assessment 1 - Basics
on: push

jobs:
    basic-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print the messages and GitHub username
              run: |
                echo "Assessment 1 Started"
                echo "Github User = ${{ github.actor }}"
