name: Assessment 1 - Basics
on: 
    push:
        branches:
            - main

jobs:
    basic-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print the initial messages 
              run:
                echo "Assessment 1 Started"

            - name: Printing Github Username
              run: 
                echo " Github User = ${{ github.actor }}"
                

