name: Main pipeline
on:
    push:
        branches:
            - main

jobs:
    call-notify-reuable:
        uses: ./.github/workflows/notify-reuable.yml
        with:
            app_name: "Mywebsite"